spring:
  application:
    name: orientasi
    
  # Database Configuration
  datasource:
    url: jdbc:sqlserver://${DB_HOST:10.226.60.31}:${DB_PORT:49705};databaseName=${DB_NAME:pcs8_orientasi};encrypt=true;trustServerCertificate=true
    username: ${DB_USERNAME:admin.pcs8}
    password: ${DB_PASSWORD:SQL2022}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true 
    
  # LDAP Configuration
  ldap:
    urls: ldap://10.225.60.10:389
    base: dc=devojk,dc=go,dc=id

server:
  port: 8080
  servlet:
    context-path: /api