ci_access:
  projects:
    - id: "pcs-8/test-orientasi"
    - id: "pcs-8/test-orientasi-react"

user_access:
  access_as:
    agent: {}
  projects:
    - id: "pcs-8/test-orientasi"         # Backend
    - id: "pcs-8/orientasi-frontend-test" # Frontend