name: Build & Deploy to OpenShift

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: self-hosted

    env:
      REGISTRY: image-registry.openshift-image-registry.svc:5000
      NAMESPACE: test-orientasi
      IMAGE_NAME: backend-orientasi

    steps:
      - uses: actions/checkout@v4

      - name: Build image with podman
        run: |
          podman build -t image-registry.openshift-image-registry.svc:5000/$NAMESPACE/$IMAGE_NAME:latest .

      - name: Push image
        run: |
          podman push image-registry.openshift-image-registry.svc:5000/$NAMESPACE/$IMAGE_NAME:latest

      - name: Restart deployment
        run: |
          oc rollout restart deployment/$IMAGE_NAME -n $NAMESPACE
