name: Build & Deploy to OpenShift

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: self-hosted

    env:
      REGISTRY: image-registry.openshift-image-registry.svc:5000
      NAMESPACE: test-orientasi
      IMAGE_NAME: backend-orientasi

    steps:
      - uses: actions/checkout@v4

      - name: Trigger OpenShift Build
        run: |
          oc start-build backend-orientasi -n test-orientasi --follow
      - name: Rollout restart
        run: |
          oc rollout restart deployment/backend-orientasi -n test-orientasi

