name: Build & Deploy to OpenShift

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: self-hosted

    env:
      # Menggunakan internal registry service agar lebih cepat (sesama cluster)
      REGISTRY: image-registry.openshift-image-registry.svc:5000
      NAMESPACE: test-orientasi

    steps:
      - uses: actions/checkout@v4
      
      - name: Trigger OpenShift Build
        run: |
          oc start-build backend-app -n ${{ env.NAMESPACE }} --follow

      - name: Rollout restart
        run: |
          oc rollout restart deployment/backend-app -n ${{ env.NAMESPACE }}
          
          oc rollout status deployment/backend-app -n ${{ env.NAMESPACE }}