name: Build & Deploy to OpenShift

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: self-hosted

    env:
      REGISTRY: image-registry.openshift-image-registry.svc:5000
      NAMESPACE: test-orientasi
      IMAGE_NAME: backend-orientasi

    steps:
      - uses: actions/checkout@v4

      - name: Login to OpenShift
        run: |
          oc login --token=${{ secrets.OCP_TOKEN }} \
            --server=${{ secrets.OCP_SERVER }} \
            --insecure-skip-tls-verify=true

      - name: Login registry
        run: |
          docker login $REGISTRY \
            -u $(oc whoami) \
            -p $(oc whoami -t)

      - name: Build image
        run: |
          docker build -t $REGISTRY/$NAMESPACE/$IMAGE_NAME:latest .

      - name: Push image
        run: |
          docker push $REGISTRY/$NAMESPACE/$IMAGE_NAME:latest

      - name: Rollout
        run: |
          oc rollout restart deployment/$IMAGE_NAME -n $NAMESPACE